### ISSUE TITLE
Why ~~ is needed?

### ISSUE THREAD

**Issue by tgbMedia** [theFunkegamer/VirusSpread#2]
https://github.com/theFunkegamer/VirusSpread/blob/e303aafaf48129e8a09f060516d73763bbb7d1f1/models/Area.js#L58

**Comment by roieGolst** [comment]
to make sure that the distance values will always be an integer number.
you can take a look about this [article ](http://rocha.la/JavaScript-bitwise-operators-in-practice)that explain you what's meaning of "Bitwise NOT - The ~ operator"
